
# Decap CMS Configuration
backend:
  name: git-gateway
  branch: main # Branch to update

# Media folder path (relative to public)
media_folder: "public/lovable-uploads"
public_folder: "/lovable-uploads"

# Enable local backend for local development
local_backend: true

# Configuration collections
collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title (Italian)", name: "titleIT", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Date (Italian)", name: "dateIT", widget: "string" }
      - { label: "Author", name: "author", widget: "string", default: "Luciano Tumminello" }
      - { label: "Author Image URL", name: "authorImageUrl", widget: "string", default: "/lovable-uploads/56f210ad-b756-429e-b8fd-f28fbbee4cfc.png" }
      - { label: "Featured Image", name: "imageUrl", widget: "image" }
      - { label: "Desktop Image", name: "desktopImageUrl", widget: "image" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Category (Italian)", name: "categoryIT", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Tags (Italian)", name: "tagsIT", widget: "list" }
      - { label: "Excerpt", name: "excerpt", widget: "text" }
      - { label: "Excerpt (Italian)", name: "excerptIT", widget: "text" }
      - { label: "Reading Time", name: "readingTime", widget: "string" }
      - { label: "Reading Time (Italian)", name: "readingTimeIT", widget: "string" }
      - { label: "Body", name: "content", widget: "markdown" }
      - { label: "Body (Italian)", name: "contentIT", widget: "markdown" }
      - { label: "Published", name: "published", widget: "boolean", default: true }

