
backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} \"{{slug}}\""
    update: "Update {{collection}} \"{{slug}}\""
    delete: "Delete {{collection}} \"{{slug}}\""
    uploadMedia: "Upload \"{{path}}\""
    deleteMedia: "Delete \"{{path}}\""

media_folder: "public/uploads"
public_folder: "/uploads"

# For local development only - to be removed in production
local_backend: true

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Title (Italian)", name: "titleIT", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", pattern: ['^[a-zA-Z0-9-]+$', "Must be URL friendly - use only letters, numbers, and hyphens"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Date (Italian Format)", name: "dateIT", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Luciano Tumminello"}
      - {label: "Author Image URL", name: "authorImageUrl", widget: "string", default: "https://www.lucianotumminello.com/lovable-uploads/56f210ad-b756-429e-b8fd-f28fbbee4cfc.png"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Category (Italian)", name: "categoryIT", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Tags (Italian)", name: "tagsIT", widget: "list"}
      - {label: "Reading Time", name: "readingTime", widget: "string"}
      - {label: "Reading Time (Italian)", name: "readingTimeIT", widget: "string"}
      - {label: "Featured Image", name: "desktopImageUrl", widget: "image", required: true}
      - {label: "Mobile Image", name: "imageUrl", widget: "image", required: true}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Excerpt (Italian)", name: "excerptIT", widget: "text"}
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "Content (Italian)", name: "contentIT", widget: "markdown"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
