
backend:
  name: git-gateway
  branch: main

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Title (Italian)", name: "titleIT", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Date (Italian)", name: "dateIT", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "Luciano Tumminello"}
      - {label: "Author Image", name: "authorImageUrl", widget: "string"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Category (Italian)", name: "categoryIT", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Tags (Italian)", name: "tagsIT", widget: "list"}
      - {label: "Reading Time", name: "readingTime", widget: "string"}
      - {label: "Reading Time (Italian)", name: "readingTimeIT", widget: "string"}
      - {label: "Featured Image", name: "desktopImageUrl", widget: "image"}
      - {label: "Mobile Image", name: "imageUrl", widget: "image"}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Excerpt (Italian)", name: "excerptIT", widget: "text"}
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "Content (Italian)", name: "contentIT", widget: "markdown"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
